### PR TITLE
feat: add redirectUrl as a constructor option

### LINKED ISSUE #367: [FEAT]: add `redirectUrl` to constructor option
### Describe the need

Testing OAuth apps locally is hard-ish. Multiple OAuth callback URLs can now be registered for GitHub/OAuth Apps, but when running the server locally, the `redirectUrl` argument has to be passed to `/api/github/oauth/login?redirectUrl=...`.

It would be more elegant if we could pass a default redirectUrl to the OAuthApp constructor instead:

```js
const app = new OAuthApp({
  clientType: "oauth-app",
  clientId: "1234567890abcdef1234",
  clientSecret: "1234567890abcdef1234567890abcdef12345678",
  redirectUrl: process.env.NODE_ENV === "production" ? PRODUCTION_URL : "http://localhost:3000"
});
```

### SDK Version

@octokit/oauth-app@4.1.0

### API Version

n/a

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SayakMukhopadhyay**
Resolves #367

----

### Before the change?

* The redirect url was only able to be set as a login url parameter

### After the change?

* The redirect url now can also be set as a constructor option.
* If both are set, the login url parameter is taken precedence

### Other information

* None

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Feature/model/API additions: `Type: Feature`

----

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
A+ PR, would merge again :D 

Bonus points if you a separate commit with only the tests first next time, so that we see the ❌, then push the fix/feat commits to get the ✅ . That way we can see right away that the tests actually failed before your implementation

**Review by gr2m — CHANGES_REQUESTED** [review]
ahhh forgot one thing: could you update the [Constructor options in the README](https://github.com/octokit/oauth-app.js#constructor-options) please?

**Review by gr2m — APPROVED** [review]
Thank you, really great work 💐💝

**Comment by SayakMukhopadhyay** [comment]
Thank you for looking into the PRs so quickly.

**Pull request merged**
